#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app_lucky_number:
#  path: /lucky/number
#  controller: App\Controller\LuckyController::

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"